@PolicyReporter.Server_HostAddress = http://localhost:5091

###

GET {{PolicyReporter.Server_HostAddress}}/policyreport
Accept: application/json

###

GET {{PolicyReporter.Server_HostAddress}}/policyreport?activeOnly=true
Accept: application/json

###

GET {{PolicyReporter.Server_HostAddress}}/policyreport?broker=1&activeOnly=true
Accept: application/json

###

GET {{PolicyReporter.Server_HostAddress}}/policyreport?broker=broker2&activeOnly=false
Accept: application/json

###